name: CI Pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv

    - name: Create Conda environment
      run: |
        conda install -c conda-forge mamba
        mamba install -c conda-forge fenics-dolfinx

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest test/

    - name: Cleanup
      run: |
        conda deactivate