name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - name: Install fenicsx
      run: mamba install -c conda-forge fenics-dolfinx mpich
    - name: Install dependencies
      run: pip install pytest pytest-cov
    - name: Run tests
      run: python3 -m pytest test/ --cov festim --cov-report xml --cov-report term