name: ci

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true

      - name: Install fenicsx
        run: mamba install -c conda-forge fenics-dolfinx

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run tests
        run: python3 -m pytest test/