name: ci

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mamba-org/setup-micromamba@v1
        with: 
          environment-name: test-env
          create-args: >-
            python=3.10
            numpy

      - name: Install fenicsx
        run: mamba install -c conda-forge fenics-dolfinx

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run tests
        run: python3 -m pytest test/