name: CI

on: 
  pull_request:
    branches: 
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba
    - name: Install fenics
      run: |
        mamba install -c conda-forge fenics-dolfinx
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov
    - name: Run Tests
      run: |
        python3 -m pytest test/
      