name: Run tests
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        mamba-version: "*"
        channels: conda-forge, defaults

    - name: Create Conda environment
      shell: bash -l {0}
      run: |
        mamba install -c conda-forge fenics-dolfinx

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install pytest pytest-cov

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest test/
