name: CI Pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Conda environment
      run: |
        conda create -n myenv python=${{ matrix.python-version }}
        conda activate myenv
        mamba install -c conda-forge fenics-dolfinx

    - name: Install dependencies
      run: |
        # You can install other project-specific dependencies here
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Cleanup
      run: |
        conda deactivate